### ISSUE TITLE
Fatal Error beim Aktivieren des Plugins

### ISSUE THREAD

**Issue by Zodiac1978** [thefuxia/Germanix-WordPress-Plugin#6]
Ich bekomme folgende Fatal Error beim Aktivieren der Plugins:
Parse error: syntax error, unexpected T_STATIC, expecting T_OLD_FUNCTION or T_FUNCTION or T_VAR or '}' in /pages/bf/4f/d0006222/home/htdocs/public_html/cms/wp-content/plugins/toscho-Germanix-WordPress-Plugin-765b3dd/germanix_translate.php on line 36

Parse error: syntax error, unexpected T_STATIC, expecting T_OLD_FUNCTION or T_FUNCTION or T_VAR or '}' in /pages/bf/4f/d0006222/home/htdocs/public_html/cms/wp-content/plugins/toscho-Germanix-WordPress-Plugin-765b3dd/germanix_url.php on line 62

PHP 4.4.9 auf einem Strato Managed Server. Ist PHP5 womöglich Voraussetzung? Habe keine Voraussetzungen auf der Pluginseite gefunden ...

**Comment by thefuxia** [comment]
Ja, PHP 5 setze ich voraus. Das ist sieben Jahre alt, da weise ich nicht mehr drauf hin. ;)

**Comment by Zodiac1978** [comment]
Sag' das mal Strato ... ;-)

**Comment by thefuxia** [comment]
Der erste Treffer bei der Suche nach »PHP5 Strato«: http://www.script-artists.de/2008/01/wieder-was-gelernt-strato-und-php5.html ;)

**Comment by Zodiac1978** [comment]
Danke für den Hinweis. Beim Managed Server geht nur der Weg über die htaccess und so weit ich das sehen kann gibt es dabei auch keine Geschwindigkeitseinbußen (Im Gegensatz zum PHP5 CGI-Modul bei älteren all-inkl..com-Servern.)
Für alle, die auch bei Strato mit einem Managed Server sind, hier der Weg dafür: 
http://www.strato-faq.de/artikel.html?id=401
