### ISSUE TITLE
How about "merging" efforts for a (complete) DE plugin?

### ISSUE THREAD

**Issue by cfoellmann** [thefuxia/Germanix-WordPress-Plugin#9]
Please have a look here: https://github.com/bueltge/de_DE.php/issues/7

**Comment by thefuxia** [comment]
Ich bin mit Franks Organisation des Codes gar nicht einverstanden. Derzeit gibt es kaum Überschneidungen, und die Reibungskosten der Zusammenarbeit wären sicher zu hoch.

Mittelfristig werden ich mich auf [T5 Rewrite](https://github.com/toscho/t5-rewrite) konzentrieren und die Transliterationen aus Germanix dort erweiterbar einbauen. Es wird also eine Optionsseite dafür geben. 

Einige deutsche Nicht-ASCII-Zeichen werden inzwischen ja auch von WordPress korrekt erfasst, so dass die Fokussierung aufs Deutsche keinen Sinn mehr ergibt.

**Comment by cfoellmann** [comment]
ok. hört sich logisch an.

Ich habe auch schon gemerkt, dass es schwierig würde sich auf eine Basis zu einigen.

**Comment by bueltge** [comment]
Man muss doch aber verbal die gemeinsamen Ziele erfassen können. Alle Lösungen sind unterschiedlichen entstanden, gereift. Nun stichpunktartig einen gemeinsamen Nenner zu finden, könnte helfen ein Basisplugin entstehen zu lassen. Ebenso könnte daraus ein gemeinsame Readme entstehen, die es den Nutzern einfacher macht, sich für eine Lösung zu entscheiden und so erübrigt sich ggf. die Pflege für die eine oder andere Lösung.

**Comment by thefuxia** [comment]
Ich möchte eine möglichst umfassende, wenn nicht gar vollständige [Normalization Form KD](http://unicode.org/reports/tr15/#Norm_Forms) implementieren. Die werde ich in ein von WordPress losgelöstes Model schreiben, dessen Ausgabe dann teilweise durch die Übersetzungsfilter läuft. Ich denke, das liegt ein wenig außerhalb des Impetus’ eurer Plugins.

**Comment by bueltge** [comment]
Wohl war, etwas sehr mächtiges.

**Comment by thefuxia** [comment]
Die langfristige Idee dabei ist, daß man die Normalisierungsfunktionen auch an anderer Stelle verwenden kann, bei der Suche etwa. Momentan versteht WordPress ja nicht, daß `möglich` und `moeglich` dasselbe Wort meinen, wenn man etwas sucht.

**Comment by bueltge** [comment]
Ich weiß wo du hin willst; aber WordPress ist nicht so weit und daher denke ich, dass du damit viel Arbeit hast.

**Comment by cfoellmann** [comment]
Was für mich so unbegreiflich ist, dass es für die Thematik nicht mehr Bedarf gibt. Warum gibt es in der DE-Community von WP eigentlich kein DE-Plugin Projekt, das genau diese Thematik angreift?
Umlaute in Permalinks, Umlaute in Suchen, ... Das ist doch für jede deutsche Seite interessant, oder?

**Comment by bueltge** [comment]
Vermutlich nicht präsent genug im Alltag, die Leute schaue da wenig hin und die Masse ignoriert.

**Comment by cfoellmann** [comment]
Wenn man mal davon absieht, dass du @bueltge gerne die dropin-Form erhalten möchtest, würde mich mal interessieren ob sich genug DE-Entwickler "rekrutieren" ließen um an einem "offiziellen" DE-Plugin zu arbeiten. Dies könnte mit den bisher in den 3 Projekten enthaltenen Funktionen bestehen und dann um Hook-ins zur Suche und weiteres erweitert werden.

**Comment by bueltge** [comment]
Dropin und Plugin beißen sich ja nicht, passt daher aus meiner Sicht. Ansonsten könnten wir zumindest im 2er Team eine Lösung aus den beiden bestehenden bauen. Stichpunktartig die Ziele definieren und eine Klasse erstellen die sich kümmert. Parallel könnten wir später Funktionen rein nehmen, die Optionen brauchen - wenn nötig. Damit könnte man zumindest nur eine Lösung warten und nicht gleich die eierlegende Wollmichsau erstellen.

**Comment by thefuxia** [comment]
@cfoellmann Es kommt eben darauf an, um welches Problem herum man Lösungen bündeln möchte:
- URLs und deren Manipulation: T5 Rewrite 
- Kollisionen der deutschen Sprache mit den Voreinstellungen WPs: de_DE.php oder ein Äquivalent

Parallelen im Code bedeuten nicht, daß man dasselbe Problem löst und deshalb alles zusammenwerfen kann. :)

Ich würde die Manipulation der Suche _nicht_ in T5 Rewrite einbauen; das ist mir als Problem schon zu weit weg.

Für einen Fokus auf eine Sprache allein sehe ich keinen guten Grund mehr. Dazu sind die Probleme in anderen Sprachen zu ähnlich (Dänisch beispielsweise).

**Comment by cfoellmann** [comment]
Das hört sich logisch an, nur kann ich leider nichts zu anderen Sprachen außer Englisch und Deutsch sagen.
